# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eloCPP <- function(pwc, scores, num) {
    .Call('_quickPWCR_eloCPP', PACKAGE = 'quickPWCR', pwc, scores, num)
}

reservoirSampling <- function(indexs, k) {
    .Call('_quickPWCR_reservoirSampling', PACKAGE = 'quickPWCR', indexs, k)
}

